Mark worker s3-bucket flag as required
Because it is. Example output:

```
$ ./bin/sanaa worker
Error: the S3 bucket name cannot be empty, set --s3-bucket
Usage:
  sanaa worker [flags]

Flags:
      --concurrency int    number of conversion jobs that can be processed at a time, maximum is 10 (default 2)
  -h, --help               help for worker
      --max-retries int    maximum number of times to retry a job on failure (default 1)
      --s3-bucket string   the name of the S3 bucket to use when storing rendered files

Global Flags:
      --redis-host string        host of redis server (default "127.0.0.1")
      --redis-namespace string   namespace to use when storing data in redis server (default "sanaa")
      --redis-port int           port of redis server (default 6379)
  -v, --verbose                  verbose output for debugging

failed executing command, the S3 bucket name cannot be empty, set --s3-bucket
```